### ISSUE TITLE
Can't assign billing group

### ISSUE THREAD

**Issue by Lange0x194** [HewlettPackard/squest#305] opened 2022-01-04 09:28 UTC
I went to //siam014.gre.hpecorp.net/service/2/request/ and just to get a handson feeling of Squest, I played with it trying to create a VM but couldn’t assign a billing group. Hence the VM creation failed

**Comment by Sispheor** [comment] 2022-01-04 09:32
Hi Mathijs.
This belong to the usage of our own instance of Squest. It's not a bug. 

I close this one and I'll contact you.

**Closed by Sispheor** 2022-01-04 09:32 UTC

**Comment by Lange0x194** [comment] 2022-01-04 09:36
OK, np - thx
