### ISSUE TITLE
Custom states and operations for instances

### ISSUE THREAD

**Issue by TheToto318** [HewlettPackard/squest#765] opened 2024-01-22 17:27 UTC
Hello,

First I would like to say thanks for this great solution to provide automation for end user. We are planning to use Squest to enable our users to get a bootstrapped k8S mono node cluster in a single GCP VM. Deploying and deleting the VM is working great with the provided operations and states within Squest.
However, we would like to enable our users to start and stop their VM by using a specific playbook for GCP. It seems that Squest lacks instance states to match our need.
We imagined using the update operation to stop/start our VM and use an API call to Squest to change the VM status accordingly in "User spec" or "Admin spec" within Squest and edit the instance state. 
But there is no current state to match the power state of a VM, which would let us delegate a specific set of operations to the users (start VM, stop VM...).

_Describe a feature request:_
Custom states with specific linked operations to enable more flexibility in resources management.

Regards,
Thomas

**Comment by Sispheor** [comment] 2024-01-22 18:18
Hi,
Sorry but an instance state is not related to the state of the backend object.
Even if stopped, in your case, the VM is still provisioned. So the instance is available. 

States are part of a state machine which is hard coded by design. It's not possible to add or update state.

**Comment by Sispheor** [comment] 2024-01-24 15:15
I close this one.
You need to use day 2 operations and set your custom state in the instance specs.
You can also add a custom link in your instance that would propose to "start" or "stop" the VM.

Have fun with Squest !

**Closed by Sispheor** 2024-01-24 15:15 UTC

**Comment by Sispheor** [comment] 2024-01-24 15:45
No the "custom state" would be just a data placed into the instance spec. Nothing related to the real "Squest instance state" like "AVAILABLE".

[Custom link doc here](https://hewlettpackard.github.io/squest/2.5.0/manual/administration/extras/#custom-links)

Those links are then shown in the instance details page.
So you could have a button that show the current "custom state" of your VM like "Powered off". And the URL behind this button could point to a day 2 operations that power on the VM.

You could have one button named "Power on" with a when condition set to `spec['vm_state'] == 'off'` and another button named "Stop VM" with a when condition set to  `spec['vm_state'] == 'on'`
